---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: aircon
  name: aircon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aircon
    spec:
      containers:
      - env:
        - name: GCP_CONFIG
          value: "./lib/jwt"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/gcpconfig.json
        - name: FIREBASE_CONFIG
          value: /var/secrets/firebase/firebase-key.json
        image: gcr.io/phev-db3fa/github.com/phev-remote/aircon:9e4144a
        name: aircon
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        volumeMounts:
        - mountPath: /var/secrets/firebase
          name: firebase-key
        - mountPath: /var/secrets/google
          name: gcloud-config-key
      volumes:
      - name: firebase-key
        secret:
          defaultMode: 420
          secretName: firebase-key
      - name: gcloud-config-key
        secret:
          defaultMode: 420
          secretName: gcloud-config-key