---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: aircon
  name: aircon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aircon
    spec:
      containers:
      - env:
        - name: GCP_CONFIG
          value: "./lib/jwt"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/gcpconfig.json
        - name: FIREBASE_CONFIG
          value: /var/secrets/firebase-key.json
        image: gcr.io/phev-db3fa/aircon:ba650e4
        name: aircon
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/secrets
          name: secret-keys
      volumes:
      - name: secret-keys
        secret:
          defaultMode: 420
          secretName: firebase-key