apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2018-11-04T00:02:41Z
  generation: 2
  labels:
    run: aircon
  name: aircon
  namespace: default
  resourceVersion: "43542"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/aircon
  uid: f2a3c8b3-dfc4-11e8-acc5-080027b16aec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: aircon
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: aircon
    spec:
      containers:
      - env:
        - name: GCP_CONFIG
          value: "./lib/jwt"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/gcpconfig.json
        - name: FIREBASE_CONFIG
          value: /var/secrets/firebase/firebase-key.json
        image: gcr.io/phev-db3fa/github.com/phev-remote/aircon:9e4144a
        imagePullPolicy: Always
        name: aircon
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/secrets/firebase
          name: firebase-key
        - mountPath: /var/secrets/google
          name: gcloud-config-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: firebase-key
        secret:
          defaultMode: 420
          secretName: firebase-key
      - name: gcloud-config-key
        secret:
          defaultMode: 420
          secretName: gcloud-config-key
status:
  conditions:
  - lastTransitionTime: 2018-11-04T00:02:41Z
    lastUpdateTime: 2018-11-04T00:02:41Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-11-04T00:02:41Z
    lastUpdateTime: 2018-11-04T22:00:45Z
    message: ReplicaSet "hello-node-55854bfd4f" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
