steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/npm'
  args: ['build']  
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--rm', '--privileged', 'multiarch/qemu-user-static:register', '--reset']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/phev-db3fa/github.com/phev-remote/aircon:arm32v7','-f','Dockerfile.arm32v7','.']